### ISSUE TITLE
"rememberable" module not obeying autoRecall

### ISSUE THREAD

**Issue by film42** [heartsentwined/ember-auth#72] opened 2013-07-02 18:07 UTC
Everything is working great except `rememberable` does not `autoRecall`.

The strange thing is that if I do `App.Auth.get('module.rememberable').recall()` then it makes the request and works, so I know it's not a configuration problem.

I even experimented with the example app, literally copying everything verbatim and still nothing. Perhaps this is a bug because I use `baseUrl: 'http://localhost:3000'` ?

``` coffeescript
window.App = App = Ember.Application.create()

App.Auth = Ember.Auth.create
  baseUrl: 'http://localhost:3000'

  signInEndPoint: '/login'
  signOutEndPoint: '/logout'

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'

  modules: ['emberData', 'rememberable']

  rememberable:
    tokenKey: 'remember_token'
    period: 14
    autoRecall: true
```

So here's a run down:

```
App.Auth.signIn({data: {email: 'test@example.com', password: '123', remember: true}});
=> No errors
App.Auth.get('userId')
=> "film42"
[ REFRESH THE PAGE, NO SERVER REQUEST MADE ]
App.Auth.get('userId')
=> undefined
App.Auth.get('module.rememberable').recall()
=> No errors
App.Auth.get('userId')
=> "film42"
```

I hope I'm not missing something obvious, thanks!

**Comment by film42** [comment] 2013-07-02 18:40
I can add the following right below it to make it _kinda_ work

``` coffeescript
# Force a login if not already signedIn
App.Auth.get('module.rememberable').recall() unless App.Auth.get('signedIn')
```

**Comment by heartsentwined** [comment] 2013-07-03 02:56
I cannot reproduce the issue. Here is what I did:

``` sh
$ git clone https://github.com/heartsentwined/ember-auth-rails-demo
$ bundle install
$ echo "  baseUrl: 'http://localhost:5000'" >> app/assets/javascripts/auth.coffee
$ foreman start
```

Then, I go to the console, and

``` javascript
EmberAuthRailsDemo.Auth.signIn({data: {email: 'foo@example.com', password: 'foopassword', remember: true}});
// no error
EmberAuthRailsDemo.Auth.get('userId');
// => 1
// [refresh browser]
// [a sign-in request has been made]
EmberAuthRailsDemo.Auth.get('userId');
// => 1
```

**Comment by heartsentwined** [comment] 2013-07-03 02:59
I used `localhost:5000` instead of `localhost:3000`, because the demo app uses the `5000` port. But that shouldn't make a difference.

**Comment by film42** [comment] 2013-07-03 03:00
I'll take a look at what it could be. I'll get back to you in a bit. Thanks!

**Comment by film42** [comment] 2013-07-05 15:33
Found the solution after matching dependencies.

First I thought it might be a jquery miss-match, as my app is using jquery 2, downgraded, nothing.

Next I noticed I had Ember `rc 5`, so I upgraded to `rc 6` and problem solved! (I also tried `rc 6` with jquery 2 and it worked fine).

`rememberable, authRedirectable, actionRedirectable`  are broken in `Ember 1.0.0-rc.5`, solution: upgrade.

Perhaps you should added a message like, "please ensure you're running the latest version of Ember as some older versions can break functionality"

**Comment by heartsentwined** [comment] 2013-07-05 15:50
The `7.x` branch does require ember `rc6` or above.

Closing since the original issue is resolved; and the suggestion is already adopted.

**Closed as completed by heartsentwined** 2013-07-05 15:50 UTC
