### ISSUE TITLE
I can't get current user using @auth

### ISSUE THREAD

**Issue by seifsallam** [heartsentwined/ember-auth#117] opened 2013-10-17 10:59 UTC
`@auth.user` doesn't seem to be working. I don't know if it is an ember-data issue or not. But `@auth.signIn` and `@auth.signedIn` seems to be working perfectly fine. And all requests gets send via `?auth_token=`.

Printing @auth in console returns undefined in all those fields. Any ideas where the problem might be?

**Comment by seifsallam** [comment] 2013-10-18 06:57
Also `@auth.destroySession()` doesn't seem to be working either, and `@auth.signOut()` doesn't read AJAX headers

**Comment by ekampp** [comment] 2013-10-18 09:31
I believe that the syntax is `@auth.get('user')`. Hope it helps.

**Comment by seifsallam** [comment] 2013-10-18 09:33
Yes, but i'm using coffeeScript, so its ok. Also it is undefined from console too, when i print `this.auth`

**Comment by ekampp** [comment] 2013-10-18 09:36
My syntax was coffeescript as well ;) I believe you need to access the `user` through the standard `EmberObject#get` method. And unless you have specifically assigned the auth object to the `window`, it won't be available in the console, since coffeescript wraps all code in self-contained functions.

**Comment by seifsallam** [comment] 2013-10-18 09:39
I don't understand, you're saying that i need to set it manually after signin?

**Comment by ekampp** [comment] 2013-10-18 09:47
No. You believe you'r talking about two different cases. The first case, is how to access the the `user` through the `Auth` object. The second is how to access the `Auth` object through the console. 

To address the second one first: To access any object from the console, you need to specifically assign it to the `window`, since coffeescript wraps everything in self-contained functions. So the `Auth` object isn't readily available in the console. And I don't believe one have never been able to do `this.<anything>` in the console, since the `this` is a contextual reference.

Addressing the first issue, of gaining access to the current `user` through the `Auth` object. Since `0.9`, I believe that the `Auth` object has become a regular `EmberObject`, which means that you should get and set values through the `get` and `set` methods. So to get at the user, you should use `get('user')` instead of `.user`.

**Comment by seifsallam** [comment] 2013-10-18 10:05
About first issue. Accessing it using `@auth.get('user')` still doesn't work. I also tried removing emberData and depend on just the object provided still doesn't work. Also other data like `userId` and `authToken` doesn't seem to return anything either

About second issue, sorry i wasn't clear, i meant `@auth` from debugger console, which returns the scope.

**Comment by seifsallam** [comment] 2013-10-18 10:19
Sorry. My bad, the problem was with `tokenLocation`. I set it to 'user' when the response didn't provide any root key. 
Thanks @ekampp for your help

**Comment by ekampp** [comment] 2013-10-18 10:20
No problem. Glad it worked out. Remember to close the issue :)

**Comment by seifsallam** [comment] 2013-10-18 10:21
I still can't do `@auth.destroySession()` should i open a new issue?

**Comment by ekampp** [comment] 2013-10-18 10:29
Oh.. Didn't realise that. No. Of course not :)

**Comment by ekampp** [comment] 2013-10-18 10:30
Do you have a backend API to talk to, regarding signing users out? And how is the `destroySession` not working?

**Comment by seifsallam** [comment] 2013-10-18 10:35
I have a placeholder resource — It doesn't do anything — but http headers don't get sent (which is required for API version)

for `destroySession` it returns `TypeError {}` when i catch it using `.fail`

**Comment by ekampp** [comment] 2013-10-18 11:36
According to the "Direct session injection / destruction" section on [the documentation page](http://ember-auth.herokuapp.com/docs) the `destroySession` is for use **when you don't** want to hit the backend.

What's the message accompanying the TypeError?

**Comment by seifsallam** [comment] 2013-10-18 11:48
Yes, i was just saying that both don't work. Locally destroying session or backend signout.

Here is the error log

```
TypeError {} combined-scripts.js:2094
(anonymous function) combined-scripts.js:2094
invokeCallback ember.js:8055
(anonymous function) ember.js:8109
EventTarget.trigger ember.js:7878
(anonymous function) ember.js:8180
DeferredActionQueues.flush ember.js:5459
Backburner.end ember.js:5545
Backburner.run ember.js:5584
Ember.run ember.js:5915
hash.success ember-data.js:7277
fire jquery.js:2913
self.fireWith jquery.js:3025
done jquery.js:7400
(anonymous function)
```

**Comment by ekampp** [comment] 2013-10-18 12:02
I'm using the `signOut()` method, which works fine, given that the backend responds correctly. Don't know, why the `destroySession` isn't working as expected.

**Comment by seifsallam** [comment] 2013-10-18 12:05
`signOut()` is working, just not correct. It totally ignores global headers that i defined.

**Comment by ekampp** [comment] 2013-10-18 12:05
What headers specifically?

**Comment by seifsallam** [comment] 2013-10-18 12:06
mainly i need `accept` to specify api version

**Comment by heartsentwined** [comment] 2013-10-18 17:51
Many issues here. I'll reply one by one.

First, the confusion over ember's accessor methods. `auth.get('foo')` is the canonical way of getting any property not directly defined on the `auth` object. `auth.foo` will work in two cases: 
1. if you are using [emberscript](http://emberscript.com), where it will get expanded to `Em.get(auth, 'foo')` during compilation; 
2. if `foo` is a regular js property

When in doubt, go through the `Em.get` accessor. It will work on regular js object property too.

**Comment by heartsentwined** [comment] 2013-10-18 17:54
Grabbing a copy of some injected object in the console.

``` javascript
App.__container__.lookup('auth:main');
```

This is the internal container that `ember-auth` uses, and the same one that `ember` uses for dependency injection. It is not public API, but hey, we are debugging! Nothing is private.

You can get a list of all injected objects too, just in case you suspect that something is not injected, thus `undefined`.

``` javascript
App.__container__.cache.dict
```

**Comment by heartsentwined** [comment] 2013-10-18 18:01
`destroySession()` is meant to clear `ember-auth`'s session locally, as said, **without** hitting the backend. It will perform the normal cleanup like a sign out request (set `authToken`, `userId`, `user`, `endTime` to `null` - possibly more depending on modules; call the `strategy` adapter's `deserialize` with the object you passed to it; and fire any `signOutSuccess` hooks).

Think of it as a "duck-typing" equivalent to a normal sign out request: everything proceeds normally, `ember-auth` just pretends that your server has already returned a response, and you have already decoded (`canonicalize` on `response` adapter) the response. You then pass this canonicalized response object to `destroySession()`, so that it beings the "sign out" process.

**Comment by heartsentwined** [comment] 2013-10-18 18:06
As for the global headers, where are you setting them? `signIn()`, `signOut()` and `send()` all allow userland code to override the passed params (including overriding the auth token, for example), by passing a [`jQuery.ajax(settings)`](http://api.jquery.com/jQuery.ajax/) -style arg to it. The demo call on the docs, for example

``` coffeescript
# sign in 
@auth.signIn 
  data: 
    'email': '(email value)' 
    'password': '(password value)' 
```

is equivalent to this 

``` coffeescript
settings = 
  data: 
    'email': '(email value)' 
    'password': '(password value)' 

# add url, type, etc to settings

jQuery.ajax(settings)
```

That is, if you want to add/override headers (or something else), just refer to the [`jQuery.ajax` docs](http://api.jquery.com/jQuery.ajax/) and specify the relevant settings.

**Comment by seifsallam** [comment] 2013-10-18 18:10
Thank you for taking the time for this. But there are two issues here
1. I understand that `destroySession()` runs locally, and it want it to, but it doesn't work. It was working before ember-auth 8.0, but after migration i can't get it to run
2. Because i couldn't get `destroySession()` to work, i tried `signOut()` but when it didn't work either, because it didn't attach my ajax headers. Header get attached in `signIn()` and `send()` btw

**Comment by heartsentwined** [comment] 2013-10-18 18:28
Thanks @seifsallam , observation confirmed. I'm working on debugging it.

**Comment by heartsentwined** [comment] 2013-10-18 18:30
Ah wait, how are you calling `destroySession()`? I mean, with what arguments? (none? string? object?)

**Comment by seifsallam** [comment] 2013-10-18 18:33
i'm using it just as `@auth.destorySession()`. Does it require any arguments ?

**Comment by heartsentwined** [comment] 2013-10-18 18:34
That's a bug. Thanks for the catch! I'll make `{}` as default.

**Closed as completed** 2013-10-18 18:37 UTC

**Comment by heartsentwined** [comment] 2013-10-18 18:39
@seifsallam pushed `9.0.7` with the fix. `@auth.destroySession()` (with no arg) will now work.

**Comment by seifsallam** [comment] 2013-10-18 18:42
It works! Thanks :)

**Comment by ekampp** [comment] 2013-10-20 16:41
:+1:
