### ISSUE TITLE
Included Purl module is not compatible with AMD (Require JS)

### ISSUE THREAD

**Issue by stimg** [heartsentwined/ember-auth#92] opened 2013-08-21 07:28 UTC
ember-auth v.7.1.1

On building of the last version of the ember-auth Require JS fails with error:
"Error: lib/ember-auth.js has two many anonymous modules in it."

I think it goes about this issue: 
https://github.com/allmarkedup/purl/issues/42

I remeber that was also in the previous version and I've fixed it by moving Purl plugin out from the auth-module and adapted it as described.

**Comment by heartsentwined** [comment] 2013-08-21 09:23
Possible duplicate of #39: refer to [this comment](https://github.com/heartsentwined/ember-auth/issues/39#issuecomment-18131050) in particular.

**Comment by heartsentwined** [comment] 2013-08-21 09:33
The purl library - included at [`vendor/jquery.url.js`](https://github.com/heartsentwined/ember-auth/blob/master/vendor/jquery.url.js) - _claims_ to be AMD-compatible, though, as per their readme:

> An AMD compatible utility to parse urls and provide easy access ...

**Comment by stimg** [comment] 2013-08-21 09:36
I don't think this issue is duplicate. `ember-auth` module itself can be loaded with RequireJS with no problem. It goes about included `Purl`module. If you make described in mentioned issue changes in included in your `ember-auth.js` `Purl` module, it will work, I think. I load `cookies.js` and `purl.js` separately from `ember-auth` and define dependencies in shim section of RequireJS. But my copy of `purl.js` is changed according that issue. So each time I update `ember-auth.js` I must cut out these two plugins from your js code. :)

**Comment by stimg** [comment] 2013-08-21 13:56
> The purl library - included at vendor/jquery.url.js - claims to be AMD-compatible

may be, but in dist/ember-auth.js, which I use, an old 2.2.1 version is included directly in the code (lines 849 -- 1118). Should I take another file for development in js?

**Comment by heartsentwined** [comment] 2013-08-21 16:27
Thanks for the clarification, I have updated the `$.url` / `purl` library to the latest, and I have released a minor version bump (`7.1.2`) for this. Please try and see if it works.

**Comment by heartsentwined** [comment] 2013-10-13 18:31
The `urlAuthenticatable` module in `9.x` no longer requires - hence no longer bundles - the `$.url` / `purl` library. This renders this issue irrelevant.

The usual code-generating [docs](http://ember-auth.herokuapp.com/) and [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide) to help with the transition.

**Closed as completed by heartsentwined** 2013-10-13 18:31 UTC
