### ISSUE TITLE
Auth.RESTAdapter ignores "url" setting

### ISSUE THREAD

**Issue by joscas** [heartsentwined/ember-auth#43] opened 2013-04-26 09:51 UTC
When I do the following I continue to get requests to `localhost`:

``` javascript
App.Store = DS.Store.extend({
  revision: 11,
  adapter: Auth.RESTAdapter.create()
});
Auth.RESTAdapter.reopen({
  url: 'https://starter-app.herokuapp.com'
});
```

Using this also doesn't work:

``` javascript
App.Store = DS.Store.extend({
  revision: 11,
  adapter: Auth.RESTAdapter.create()
});
DS.RESTAdapter.reopen({
  url: 'https://starter-app.herokuapp.com'
});
```

If I do this, requests are directed to the proper host (but without `auth_token` as would be expected):

``` javascript
BaseApp.Store = DS.Store.extend({
  revision: 11,
  //adapter: Auth.RESTAdapter.create()
});
DS.RESTAdapter.reopen({
  url: 'https://starter-app.herokuapp.com'
});
```

**Comment by heartsentwined** [comment] 2013-04-26 09:54
Acknowledged. I'm working on the next version at present with lots of bug fixes, which should be released in two to three days. `Auth.RESTAdapter` would be gone, and you would be able to use the `url` setting of `DS.RESTAdapter` as expected.

**Comment by joscas** [comment] 2013-04-26 10:05
Thanks for your effort. Will hold on until next version.

**Comment by ryw** [comment] 2013-05-01 01:17
@heartsentwined I'm new to ember, trying to implement authenticated CRUD based on code here https://github.com/dgeb/ember_data_example 

I had issue with deleted record staying in list, which I'm hoping is fixed here in ember-data: https://github.com/emberjs/data/issues/911#issuecomment-17234733

I just tried updating ember + ember data to head (via ember-data-rails generator).

Now I'm getting `Uncaught TypeError: Cannot set property 'url' of undefined` in this section of the ember-auth code:

```
Auth.RESTAdapter = DS.RESTAdapter.extend({
  ajax: function(url, type, settings) {
    settings.url = url;
    settings.type = type;
    settings.context = this;
    return Auth.ajax(settings);
  }
});
```

Sounds like this is the stuff you're working on.

Any thoughts?

**Comment by heartsentwined** [comment] 2013-05-01 02:12
Sorry for that - #44 fixed this, but I have not released a new version yet. It's just a one liner -

``` javascript
//...
ajax: function(url, type, settings) {
  settings = settings || {};
  settings.url = url;
//...
```

**Comment by ryw** [comment] 2013-05-01 02:27
Ah OK — hope you're having some success on the refactoring task — your work here at ember-auth is instrumental to me deciding to push through this weekend and build my first ember app. I appreciate your effort, and hope I can help give back as I become more familiar.

**Comment by heartsentwined** [comment] 2013-05-01 03:39
The refactoring is done, I'm just finishing with the docs

**Comment by heartsentwined** [comment] 2013-05-02 07:19
@joscas the `5.x` branch should support custom `url` for `DS.RESTAdapter`. `Auth.RESTAdapter` is gone, but more generally almost every custom `Auth*` class is gone.

**Comment by heartsentwined** [comment] 2013-05-02 07:20
@ryw `5.x` branch released which incorporates the fix.

**Comment by heartsentwined** [comment] 2013-05-02 07:20
BC breaks in `5.x` version is rather dramatic, hence I haven't written an upgrade guide yet. The [docs](http://ember-auth.herokuapp.com) should help you upgrade; otherwise please feel free to ask me how to convert a specific usage.

**Comment by heartsentwined** [comment] 2013-05-02 07:21
Closing unless issue resurfaces.

**Comment by joscas** [comment] 2013-05-02 10:35
Many thanks. I'm upgrading my app and I've found an issue. Previously I used this code to conditionally display information in handlebars depending on user login status:

`{{#if Auth.authToken}}`

Now I've tried this that is not accepted by HBs:

`{{#if App.Auth.get('signedIn')}}`

What would be the proper way to do this now?

**Comment by heartsentwined** [comment] 2013-05-02 10:41
The following are all equivalents:
- javascript: `App.get('foo').get('bar')`
- javascript: `App.get('foo.bar')`
- javascript: `Ember.get('App.foo.bar')`
- handlebars: `{{App.foo.bar}}`

That's the magic behind ember + handlebars resolving `{{person.account.id}}` and the like. 

Anyway, back to your question, the solution is simply `{{#if App.Auth.signedIn}}`. The previous `{{#if Auth.authToken}}` is just a handlebars way of saying `if (Auth.get('authToken'))`.

Sorry for dropping this from the new docs, I thought this should be an ember issue. I see I should better add them back...

**Comment by joscas** [comment] 2013-05-02 10:46
Thanks for the explanation!

**Comment by joscas** [comment] 2013-05-02 11:05
Sorry for using this thread for that but here I'm stuck with another upgrade issue. I can't access the user model:

``` javascript
App.Auth.get('userId')
"5151ef3a1907738a88000001"
App.Auth.get('authToken')
"ucYfeeag4ThxGvpHsczp"
App.Auth.get('user')
null
```

This is my `App.Auth`:

``` javascript
App.Auth = Ember.Auth.create({
  signInEndPoint: '/users/sign_in',
  signOutEndPoint: '/users/sign_out',
  tokenKey: 'auth_token',
  tokenIdKey: 'user_id',
  userModel: App.User
});
```

Am I missign some step?

**Comment by heartsentwined** [comment] 2013-05-02 11:10
I'll test it out at my end, and I'll update you.

**Comment by heartsentwined** [comment] 2013-05-02 11:50
Bug confirmed. Will notify you on fix.

**Comment by joscas** [comment] 2013-05-02 15:07
One more doubt. What would be the exact implementation of this for a route?:

``` coffescript
App.SecretRoute = Ember.Route.extend App.Auth.AuthRedirectable
```

Currently I have this:

``` javascript
App.UsersShowRoute = Auth.Route.extend({
  ...
})
```

**Comment by heartsentwined** [comment] 2013-05-02 15:19
@joscas fixed the user model issue. Unfortunately, I have to introduce another BC Break for it. `userModel` now expects a string, not a class. So pass `'App.User'` instead of `App.User` to it, and it should work fine. I am staying true to [semver](http://semver.org/) though, so `6.0.0` it is.

**Comment by heartsentwined** [comment] 2013-05-02 15:30
@joscas The previous `Auth.Route` had multiple responsibilities.

If you want to redirect unauthenticated users away from the `Auth.Route`, enable the `authRedirectable` module and do the

``` javascript
App.UsersShowRoute = Ember.Route.extend(App.Auth.AuthRedirectable);
```

as you have mentioned.

If you are looking for the `authAccess` event, again you need to enable the `authRedirectable` module, and then listen to it via the _main auth object_ 

``` javascript
App.Auth.on('authRedirectable', doSomething);
```

instead of on the route itself. old equivalent: 

```
App.UsersShowRoute = Auth.Route.extend({
  init: function() {
    this.on('authRedirectable', doSomething)
  }
});
```

There had been a scoping option in the old `rememberMe` and `urlAuthentication` options, that could isolate the methods to an `Auth.Route`. This has been removed since feedback tells me that everybody just wants the function to be applied to all `Ember.Route`s. If you are looking for these functions, enable the `rememberable` and `urlAuthenticatable` modules and follow the docs on their setup.

Finally, if you have put grouped custom logic within an `Auth.Route` (auth-related logic, perhaps?), then you need to subclass `Ember.Route` in userland code, and then proceed as usual. Example:

``` javascript
App.UsersShowRoute = App.MySubclassedRoute.extend(App.Auth.AuthRedirectable);
```

Hope this helps.

**Comment by joscas** [comment] 2013-05-02 15:30
Right!, now it attempts to fetch the user but it fails because the request is not including `auth_token`. I'm not sure this is a bug or a problem with my config as there are things I haven't implemented yet.

My console shows this (see there is no token):
`Started GET "/users/5151ef3a1907738a88000001" for 127.0.0.1 at 2013-05-02 17:21:11 +0200`

And my `Auth.conf` stands currently like this:

``` javascript
App.Auth = Ember.Auth.create({
  modules: ['emberData','rememberable','authRedirectable'],
  signInEndPoint: '/users/sign_in',
  signOutEndPoint: '/users/sign_out',
  tokenKey: 'auth_token',
  tokenIdKey: 'user_id',
  userModel: 'BaseApp.User',
  rememberable: {
    tokenKey: 'remember_token',
    period: 14,
    autoRecall: true
  },
  authRedirectable: {
    route: 'sign_in'
  }
});
```

**Comment by heartsentwined** [comment] 2013-05-02 15:40
I'm sorry but I cannot reproduce it, I got the auth token sent fine
![screenshot from 2013-05-02 23 38 52](https://f.cloud.github.com/assets/2252978/454709/86f9c17e-b33e-11e2-9a51-643c3f7bb15b.png)

**Comment by heartsentwined** [comment] 2013-05-02 15:42
Reopening though until issue fixed

**Comment by joscas** [comment] 2013-05-02 15:56
Let me update everything and see if that problem remains. If it does I'll push my whole branch so that it's easier to reproduce. Currently I'm struggling with this:

``` javascript
App.UsersShowRoute = Ember.Route.extend(App.Auth.AuthRedirectable);
```

Console says: `Uncaught TypeError: Cannot read property 'AuthRedirectable' of undefined`

Also how do I have to express that in my route? Like this?:

``` javascript
App.UsersShowRoute = Ember.Route.extend(App.Auth.AuthRedirectable,{
  setupController: function(controller, model) {
    controller.set('content', model);
    this.controllerFor('application').set('currentRoute', 'show_user');
  },
  events: {
    edit: function() {
      this.transitionTo('users.edit',this.controller.get('content'));
    }
  }
});
```

**Comment by heartsentwined** [comment] 2013-05-02 15:57
@joscas is there a dev branch on your [joscas/base_app](https://github.com/joscas/base_app) or something like that? I copied your config, but I still got the auth token sent. One wild guess: perhaps it is related to this caveat?

> **Caveat**: emberjs/ember.js#2041 describes a known ember issue that causes your model to be loaded even if the route has been redirected away. Note the workaround. Explanation in the Model Loading section of [this write-up](https://github.com/heartsentwined/ember-auth/issues/29#issuecomment-17048375).
> 
> ``` coffeescript
> # Caveat workaround:
> App.SomeRoute = Em.Route.extend
>   model: ->
>     # condition necessary
>     # if SomeModel requires authentication to access
>     if App.Auth.get('signedIn')
>       SomeModel.find()
> ```

**Comment by heartsentwined** [comment] 2013-05-02 16:04
Got the problem. Move the `require auth` sprockets directive to right after app creation, but before the other parts.

`base_app.js`:

``` javascript
//= require ./store
//= require_tree ./models
//= require_tree ./controllers
//= require_tree ./views
//= require_tree ./helpers
//= require_tree ./templates
//= require ./router
//= require_tree ./routes
//= require auth <-- remove this line
//= require_self
```

`application.js`:

``` javascript
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require handlebars
//= require ember
//= require ember-data
//= require ember-auth
//= require_self
//= require auth <-- add it here
//= require base_app
BaseApp = Ember.Application.create();
//= require_tree .
```

My deepest apologies! I should have made it clear. :sob:  I will add this to the docs.

**Comment by heartsentwined** [comment] 2013-05-02 16:05
Leaving issue open until fix confirmed.

**Comment by joscas** [comment] 2013-05-02 16:33
Thanks! It almost fixes everything. Stil, I'm getting an `Uncaught ReferenceError: Auth is not defined`  error in my [index_route.js](https://github.com/joscas/base_app/blob/ember-auth5/app/assets/javascripts/routes/index_route.js)

Here's my working branch: [ember-auth-5](https://github.com/joscas/base_app/tree/ember-auth5)

**Comment by heartsentwined** [comment] 2013-05-02 16:56
It was another `index_route.js`.

Please update [users/index_route.js](https://github.com/joscas/base_app/blob/ember-auth5/app/assets/javascripts/routes/users/index_route.js):

``` javascript
//BaseApp.UsersIndexRoute = Auth.Route.extend({
BaseApp.UsersIndexRoute = Ember.Route.extend(BaseApp.Auth.AuthRedirectable,{
```

**Comment by joscas** [comment] 2013-05-02 17:09
Arghh, sorry for that :cold_sweat:
Now I get no more errors! Thanks!!!

**Comment by heartsentwined** [comment] 2013-05-02 17:48
Glad it fixed your issue.

**Closed as completed by heartsentwined** 2013-05-02 17:48 UTC
Labels: bug
