### ISSUE TITLE
Request order

### ISSUE THREAD

**Issue by rastasheep** [heartsentwined/ember-auth#45] opened 2013-04-30 12:32 UTC
Is there any way to get ember-auth to make `Auth.Module.RememberMe.recall()` request before ember data?

When i open app first time, ember data first makes request and than ember-auth set current user (in other word, that first api request is unauthorized, but user is loged in).

**Comment by heartsentwined** [comment] 2013-04-30 12:49
No. Duplicate of #29.

Summary: this is not an `ember-auth` issue. emberjs/ember.js#2041 is an issue opened specifically to address this, viz. that a `model` hook should not be called if redirection happens in the `redirect` hook.

The solution, for now, is to wrap all auth-only model calls under an `Auth.authToken` conditional, just like in the view templates.

**Closed as completed by heartsentwined** 2013-04-30 12:49 UTC
Labels: duplicate
