### ISSUE TITLE
Url updates w/ page refresh

### ISSUE THREAD

**Issue by davidsteinberger** [heartsentwined/ember-auth#24] opened 2013-04-07 17:25 UTC
It seems that `Auth.Route` protection causes some invalid url updates upon page refresh.

My router setup looks like this:

```
App.Router.map(function(match) {
    this.route("sign_in", {path: "/login"});
    this.resource("rooms", {path: "/rooms"}, function(){
        this.route("room", {path: "/room/:folder_id"});
    });
});

App.RoomsRoute = Auth.Route.extend({
    ...
});

App.RoomsRoomRoute = Auth.Route.extend({
    ...
});
```

A page refresh in route `rooms.room` (e.g. `#/rooms/room/47`), brings the user back into `rooms.room`, however the url is set back to `#/rooms`. So a subsequent refresh ends up w/ a redirect to `rooms.index`.

When I change `App.RoomsRoute` & `App.RoomsRoomRoute` back to `Ember.Route.extend({...})` everything works as expected.

Any idea what's causing this?

**Comment by jiripospisil** [comment] 2013-05-18 09:27
@dave8401 Could you share your solution to the problem? I am seeing something very similar. To use your example, refresh on `#/rooms/room/47` causes the URL to change to `#/rooms` while rendering _both_ `rooms.index` and `rooms.room` at the same time. Tested with latest ember.js and ember-auth, modules: _["emberData", "rememberable", "authRedirectable", "actionRedirectable"]_

/cc @heartsentwined

**Comment by darthdeus** [comment] 2013-05-18 12:16
I'm also experiencing this :( I tried debugging ember-auth, but wasn't really able to find the source of the issue

**Comment by jiripospisil** [comment] 2013-05-18 18:20
So it seems I missed the `signInSmart` flag in the `actionRedirectable` settings. If I set it to `true` it kinda works\* and I am redirected back to where I was. This, however, raises a question of why I didn't end up in the static `signInRoute` route in the previous case.

\* There's still something weird going on. Imagine this setting:

```
actionRedirectable: {
  signInRoute: "dashboard",
  signInSmart: true,
  signInBlacklist: ["sign_in"],
  signOutRoute: "sign_in"
},  
```

If I enter the app's root (dashboard) signed in, sign out and sign in again right after, no redirect is done I am stuck in the `sign_in` route. If I however blacklist the `dashboard` route as well, then it works fine (but of course it causes problems if the dashboard route is the last visited route in otherwise non empty history).

**Comment by heartsentwined** [comment] 2013-05-20 03:33
@mekishizufu can you post your set of routes please? I am confused, so you made `index` redirect to `dashboard` or what?

**Comment by heartsentwined** [comment] 2013-05-20 03:36
Also, which version of `ember-auth` are you using, @darthdeus and @mekishizufu ? The original issue here refers to an old version with an `Auth.Route`, which has been refactored out and its functionality split into several modules - the relevant one here should be `authRedirectable` and `actionRedirectable` if I read your use cases correctly.

**Comment by heartsentwined** [comment] 2013-05-20 03:36
Reopening issue until re-resolving.

**Comment by jiripospisil** [comment] 2013-05-20 07:58
@heartsentwined Sorry I wasn't clear enough. The dashboard route is mapped to `/`. I will create a sample app.

**Comment by heartsentwined** [comment] 2013-06-24 20:13
@mekishizufu is your sample app up yet? This issue is going nowhere because I cannot reproduce and locate the error.

**Comment by jiripospisil** [comment] 2013-06-24 20:47
Not yet, but I am not sure whether it's worth making at this point. Ember (and our apps, not using ember-auth at  the moment) has moved on to the new router, which works beautifully for auth purposes, and you are very likely  rewriting all of the modules anyway.

**Comment by heartsentwined** [comment] 2013-07-01 03:56
`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API

---

In particular, ember rc6 now guarantees same treatment between in-app transitions and those done via URL changes (or entries, or refreshes). This might solve this issue.

@mekishizufu @dave8401 @darthdeus - please try upgrading and see if the issue persists - unless you have moved away from ember-auth. However, if nobody left is using ember-auth for this issue - and I cannot reproduce the reported issue with present information - then I will close the bug for being unable to progress any further.

**Comment by heartsentwined** [comment] 2013-07-09 02:20
Closing due to inactivity.

**Closed as completed by heartsentwined** 2013-07-09 02:20 UTC
