### ISSUE TITLE
Remember Me in direct session injection 

### ISSUE THREAD

**Issue by seifsallam** [heartsentwined/ember-auth#79] opened 2013-07-15 18:34 UTC
Is there a way to tell ember-auth to remember me using session injection?

I use this for user signin after registration

**Comment by heartsentwined** [comment] 2013-07-15 21:13
Either you include a remember token in the mocked server response - the value probably doesn't matter if you don't care about it.

``` coffee
App.Auth.createSession '{"remember_token": "foo"}' # auth token, user id, etc, omitted
```

Or you use the module's methods directly.

``` coffee
# recall a user from local remembered session, if any
App.Auth.get('module.rememberable').recall()

# remember a user from last server response,
# if a remember token is present
App.Auth.get('module.rememberable').remember()

# clear local remembered sessions
App.Auth.get('module.rememberable').forget()
```

Of course you have to enable the `rememberable` module and set its settings as usual. All code taken from the [docs](http://ember-auth.herokuapp.com/docs).

**Comment by seifsallam** [comment] 2013-07-15 23:06
First one is the one i'm looking for. Thanks alot.

**Comment by seifsallam** [comment] 2013-07-15 23:09
@heartsentwined Something off topic here, do you have any plans for oAuth integration, or tips on best way to integrate with ember-auth? Authenticating from ember vs from backend

**Comment by seifsallam** [comment] 2013-07-15 23:17
Sorry, but first method doesn't seem to be saving the token, just by refreshing it was gone

**Comment by heartsentwined** [comment] 2013-07-16 02:27
Please post your full `App.Auth = Ember.Auth.create()` settings, and the `App.Auth.createSession()` call.

**Comment by heartsentwined** [comment] 2013-07-16 02:29
oAuth integration: yes, in a future version maybe. For now, you can check out @joscas' example app, he has made an ember-auth + oAuth demo app.

**Comment by seifsallam** [comment] 2013-07-16 07:58
Here is code

``` coffee
## auth.coffee

App.Auth = Ember.Auth.create(

  modules: [
    'emberData'
    'rememberable'
    'authRedirectable'
    'actionRedirectable'
  ]

  signInEndPoint: '/sessions'
  signOutEndPoint: '/sessions'

  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'

  userModel: 'App.User'

  rememberable:
    tokenKey: 'remember_token'
    period: 14
    autoRecall: true

  authRedirectable:
    route: 'index'

  actionRedirectable:
    # signInRoute: 'index'
    signInSmart: true
    signInBlacklist: ['signin'] # default []
    signOutRoute: 'index'
    signOutSmart: true
    signOutBlacklist: ['signout'] # default []

)


## users_controller.coffee

App.UsersNewController = Ember.ObjectController.extend(
  save: ->
    self = this
    @content.save().then ->
      userId = self.get 'id'
      metadata = App.store.typeMapFor(App.User).metadata
      authToken = metadata.token
      rememberToken = metadata.remember
      message = metadata.message

      App.Auth.createSession '{"user_id": "' + userId + '", "auth_token": "' + authToken + '", "message": "' + message + '", "remember_token": "' + rememberToken + '"}'
      self.transitionToRoute 'index'
```

And this is the response from creating a new user

``` json
{
    "user":{},
    "meta":{
        "message":"Hi, Ray",
        "token":"VFpwfL5gm21cypThjNx4",
        "remember_token":"51e4fdf70eae9c03cd000001-$2a$10$B65dTzc9rZQ/aDw7aw5cxe"
    }
}
```

**Comment by heartsentwined** [comment] 2013-07-16 10:34
Thanks, I'll take a look at that.

**Comment by heartsentwined** [comment] 2013-07-26 22:00
One issue: does signing in with the given `remember_token` gives a valid response? I can partly reproduce your issue, but only when the stored remember token is invalid.

Success scenario:
1. Load app
2. Call `App.Auth.createSession('{"user_id":1, "auth_token":"foo", "remember_token": "bar"}');`
3. At the same time, the server saves the remember token `bar`
4. Refresh
5. Now, since you have enabled `autoRecall` of the rememberable module, `ember-auth` tries to sign in with the token `bar`.
6. Server gives successful response, including the new remember token
7. Remember cookie gets updated to new remember token

Failure scenario:
1. Load app
2. Call `App.Auth.createSession('{"user_id":1, "auth_token":"foo", "remember_token": "bar"}');`
3. (The remember token `bar` is not saved at server-side.)
4. Refresh
5. Now, since you have enabled `autoRecall` of the rememberable module, `ember-auth` tries to sign in with the token `bar`.
6. Server gives failure response
7. Remember cookie gets cleared

Is this the cause of your issue?

**Comment by seifsallam** [comment] 2013-07-27 09:29
No, I double checked my access and token is correct. In regular remember me scenario if it is set to false `ember-auth` doesn't save `remember_token` in cookies, but in cause of omniauth callback, it saves the `remember_token`, but it gets removed after refresh.

Here is the URL after the callback, do you think this would be the problem? `http://localhost:9000/?auth[user_id]=51f39174b2fac0f375000001&auth[auth_token]=Fb6GadLMHqL9oCJxicLd&auth[remember_token]=51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6/bgu/#/posts`

**Comment by heartsentwined** [comment] 2013-07-27 09:40
I noticed one particularity: there is a slash in your remember token. Your callback URL gives

```
...&auth[remember_token]=51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6/bgu/#/posts
```

Notice that towards the end of your remember token, in `..GO6/bgu`, the slash is not encoded. So the token will end prematurely before the slash, shortening it to an invalid token.

Can you check at server logs, about how it responses to ember-auth requests? i.e. what it is doing at:
1. initial call of `save` in client app
2. what it sends back
3. what it does when you refresh the app
4. once again what it sends back

**Comment by heartsentwined** [comment] 2013-07-27 09:42
In any case, if it is "working perfectly" for regular sign in, but only errors on omniauth, then we can be pretty sure that the issue lies with the omniauth implementation, no?

**Comment by heartsentwined** [comment] 2013-07-27 09:44
Another note: your URL seems to be following the format of the `urlAuthenticatable` module, but you have not enabled it in the auth config. Is it just a coincidence? Or do you want to use `urlAuthenticatable` too? In this case you would have to decide which would override which (`urlAuthenticatable` vs `rememberable`), and specify the modules in your desired priority.

**Comment by seifsallam** [comment] 2013-07-27 10:00
Oh, thats more clear now. The response from `sessions` is `401 Unauthorized`.

I am using the same method of generating `remember_token` as in `ember-auth` documentation, and it works great in `sessions` on the other hand generating it from `omniauth_callback` doesn't seem to work. Any ideas?

``` ruby
    def remember_token(user)
      data = User.serialize_into_cookie(user)
      "#{data.first.first}-#{data.last}"
    end
```

**Comment by heartsentwined** [comment] 2013-07-27 10:08
Try url-encoding your callback.

**Comment by seifsallam** [comment] 2013-07-27 10:17
Still nothing

**Comment by seifsallam** [comment] 2013-07-27 10:19
serializer from cookie cannot find user

``` ruby
    def resource_from_remember_token
      token = params[:remember_token]
      id, identifier = token.split('-')
      User.serialize_from_cookie(id, identifier)
    end
```

**Comment by heartsentwined** [comment] 2013-07-27 10:30
What I mean is, first you want to url-encode the query string params in the callback URL, such that the callback URL should read

```
...&auth[remember_token]=51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6%2Fbgu/#/posts
```

Notice the `%2F` replacing the `/` towards the end.

Next, depending on how magic your code is, when you access the token, you may, or may not, need to manually decode the URL or the token, so that it reverts to 

```
51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6/bgu
```

instead of trying to find a token literally (with the `%2F`)

```
51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6%2Fbgu
```

which would, of course, not exist.

I suggest that you read up on url encoding, if you are not familiar with how it works, and where you need (and don't need) to apply its encode/decode methods.

**Comment by seifsallam** [comment] 2013-07-27 10:43
Still no difference with/out encoding Rails reads it as 

```
51f39174b2fac0f375000001-$2a$10$xuklo.C4CiuppHEGO6/bgu
```

**Comment by heartsentwined** [comment] 2013-07-27 10:54
Do you mean when it is sent out in response, or when it is read from params?

If it is the first case, and if you are passing it verbatim as the app's callback destination, then you need to url-encode it.

If it is the second case, then it is reading the full remember token correctly, but then still throwing a `401`, so despite all these it is still an invalid token - error elsewhere.

**Comment by seifsallam** [comment] 2013-07-27 11:56
When it reads from params. I don't know where the problem is but generating `remember_token` from `omniauthCallback` doesn't work and doesn't get saved to user.

At then end I just switched to using `urlAuthenticatable`, then added condition in sessions to check if there is `auth_token` in params. So after i get this callback, `ember-auth` calls the API back again with data from callback to login.

Thanks a lot for your help.

**Comment by heartsentwined** [comment] 2013-07-27 11:57
Well I'm still not sure where the original issue originates from, but I'll close this issue since you have found a solution. Feel free to re-open this if you wish to further debug the original issue.

**Closed as completed by heartsentwined** 2013-07-27 11:57 UTC

**Comment by seifsallam** [comment] 2013-07-27 12:01
I think this is a rails / devise issue
—

**Comment by heartsentwined** [comment] 2013-07-27 12:03
Not enough information in this thread to pinpoint though, good luck if you're debugging with your full codebase.
