### ISSUE TITLE
What about kind of "browsersessionable"?

### ISSUE THREAD

**Issue by tobiaswerner** [heartsentwined/ember-auth#62] opened 2013-05-31 18:55 UTC
If I login with valid credentials I would expect the application to log me in as I open it e.g. in another browser tab. We are of course in the same session...

I already thought about a new Devise module serializing a 'browsersessiontoken' in a session cookie - but I'm not sure if it isn't like breaking a butterfly on a wheel.
You know what I mean? I guess it's "too much". 

Any ideas I didn't mind?

//Edit:
Adapted from Devises rememberable module. Pushed into my user model.

``` ruby
field :browsersession_token, :type => String

      def ensure_browsersession_token!
        self.browsersession_token = self.class.browsersession_token
        save(:validate => false) if self.changed?
      end

      def forget_browsersessiontoken!
        return unless persisted?
        self.browsersession_token = nil if respond_to?(:browsersession_token=)
        save(:validate => false)
      end

      def browsersessionable_value
        if respond_to?(:browsersession_token)
          browsersession_token
        elsif respond_to?(:authenticatable_salt) && (salt = authenticatable_salt)
          salt
        else
          raise "authenticable_salt returned nil for the #{self.class.name} model. " \
            "In order to use rememberable, you must ensure a password is always set " \
            "or have a remember_token column in your model or implement your own " \
            "rememberable_value in the model with custom logic."
        end
      end

      def browsersessionable_options
        self.class.browsersessionable_options
      end

    protected 


        def self.serialize_into_cookie(record)
          [record.to_key, record.browsersessionable_value]
        end

        def self.serialize_from_cookie(id, browsersession_token)
          record = to_adapter.get(id)
          record if record && record.browsersessionable_value == browsersession_token
        end

        def self.browsersession_token #:nodoc:
          generate_token(:browsersession_token)
        end
```

Ember-Auth-module. More or less a stupid copy of rememberable - no cookie expiration set. 

``` javascript
class Em.Auth.Module.Browsersessionable
  init: ->
    @config? || (@config = @auth.browsersessionable)
    @patch()

  syncEvent: (name, args...) ->
    switch name
      when 'signInSuccess'  then @storeSessionCookie()
      when 'signInError'    then @deleteSessionCookie()
      when 'signOutSuccess' then @deleteSessionCookie()

  recall: (opts = {}) ->
    if !@auth.signedIn && (token = @retrieveToken())
      @fromRecall = true
      opts.data ||= {}
      opts.data[@config.tokenKey] = token
      @auth.signIn opts

  storeSessionCookie: ->
    if token = @auth.response?[@config.tokenKey]
      @storeToken(token) unless token == @retrieveToken()
    else
      @deleteSessionCookie() unless @fromRecall
    @fromRecall = false

  deleteSessionCookie: ->
    @removeToken()

  retrieveToken: ->
    @auth._session.retrieve 'ember-auth-session'

  storeToken: (token) ->
    @auth._session.store 'ember-auth-session', token

  removeToken: ->
    @auth._session.remove 'ember-auth-session'

  patch: ->
    self = this
    Em.Route.reopen
      redirect: ->
        super.apply this, arguments
        if self.config.autoRecall && !self.auth.signedIn
          self.recall { async: false }
```

Would work, if I'd implement the resource_from_browsersession_token method in session_controller.

**Comment by flynfish** [comment] 2013-06-01 00:28
Interesting, I was just thinking about  the need for something like this. Would love to hear @heartsentwined's thoughts on your solution.

**Comment by tobiaswerner** [comment] 2013-06-01 10:48
Just made a PR. 
https://github.com/heartsentwined/ember-auth/pull/64

Can I link the PR and this discussion?

//
Roughly untested devise extension here.
https://github.com/tobiaswerner/devise-browsersessionable

**Comment by heartsentwined** [comment] 2013-06-03 08:07
A good idea in general, a few thoughts:

(in no particular order, not objecting the idea, just what came to mind. also let's discuss this and #64 PR here.)
- is this feature a more ember-level concern though? If a user expects one app's session to show up on another browser tab, then this could extend to other ember app state? e.g. models?
- \- or the converse is true? that if one app's state will not apply to another app, then signed in status should not apply either
- \- yet still following the above, if we are building an app whose state will persist across "different browser tabs", then perhaps what we actually need is a server-push system to sync, at least, one user's different tabs? (I responded to this use case in [this SO question](http://stackoverflow.com/questions/16430424/handling-user-registration-in-an-ember-js-rails-devise-app/16433429#comment24286243_16433429). It feels patchy, but it is in the feature list.)
- the current implementation of `storage` adapter is catering for permanent storage; is it a side effect that omitting `{ expires: /* a value */ }` should be interpreted as expecting session storage (à la [`jquery-cookie`](https://github.com/carhartl/jquery-cookie), but not supported in [`localStorage`](http://dev.w3.org/html5/webstorage/#the-localstorage-attribute))? Or should this be treated as the official "bridge" API for these different storage adapters? Or do we need to split `storage` into `sessionStorage` and `permanentStorage`? (ref. storage is currently used by `rememberable`)
- naming - consider `sessionRememberable`? As you observed, this is mostly a duplicate of `rememberable`
- I'm unsure which direction to `DRY`up this feature. Either we make an intermediate module that shares code between `rememberable` and `sessionRememberable`, or this in fact means `sessionRememberable` should be a sub-feature in `rememberable`?
- \- continuing on this, should `sessionRememberable` interact with `rememberable`? e.g. one overriding / clearing the other's session data on a new sign in? the theoretical session clash / different sign in `session` and `remember` cookie should not make any sense in real world, and in any case, this is easily controlled by specifying module precedence.

**Comment by tobiaswerner** [comment] 2013-06-03 16:31
Thanks for sharing your thoughts about this. Let's look what I thought during the last hour..
- more a ember-level concern: you are totally right. "Sharing" application state between different tabs would mean it have to be a framework concern. Already "produced" state could in fact affect behaviour. If talking from a SinglePage app we wouldn't share state between tabs, but personally I didn't understand EmberJS as an singlepage app framework. Would love to hear what the ember core team think about this.
- I don't think storing clients state on the server would be the best. The coupling between the frontend and backend would be too strong. May the localStorage be suitable? I hadn't that much time playing and dealing with it right now.
- Didn't really get this point. In general differing between sessionStorage and permanentStorage would be best, in my opinion. 
- sessionRememberable sounds good. Still pondering for 30 minutes why this wasn't in my mind...
  Personally I prefer an intermediate module between. 
- Erasing others session on new signIn would be good. Maybe also something like "this session must not last more than 6 hours" which means the backend have to check for the time, similar to rememberable in devise.

**Comment by heartsentwined** [comment] 2013-06-03 17:52
- IMHO we should put this module on hold for now, and, as you mentioned, open an issue over at [ember](https://github.com/emberjs/ember.js) and see if they have any plans for session persistence.
- It's not like storing client state, it's more like how to maintain data consistency across a multi-user app. Simple example: user A deletes a `Foo`, and this change is propagated to the server (successfully). Should we delete that for "the other app at another browser tab" for user A? (And by extension, how about user B at the other side of the world?) Same goes for create and update actions.
- Storage methods: never mind, I'll figure that out.
- `6 hours` session limit (or whatever) would be completely left for userland implementation. A `timeoutable` module would be a good idea though.

**Comment by tobiaswerner** [comment] 2013-06-03 18:07
Yeah, agree. Lets hold this here.
Thanks for the explanation in your second point. Now I got it. 
The last point, you named it timeoutable-module, is exactly what I had in mind.

**Comment by flynfish** [comment] 2013-06-03 18:50
I just wanted to clarify... so a timeoutable module is going to be developed?

**Comment by heartsentwined** [comment] 2013-06-03 18:51
@flynfish it will.

**Closed as completed** 2013-07-10 06:45 UTC
Labels: enhancement

**Comment by heartsentwined** [comment] 2013-07-10 06:47
Closing: `timeoutable` is implemented; and the original issue should be an ember-level concern (see comments above).
